[package]
name = "chown"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "chown"
path = "chown.rs"

[lib]
name = "lib"
path = "../lib.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }